name: "WordPress Version Checker"
on:
  push:
    branches:
      - develop
      - main
  schedule:
    - cron: '0 0 * * 1'

permissions:
  issues: write

jobs:
  wordpress-version-checker:
    if: github.repository_owner == 'GatherPress'
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Version Checker
        uses: skaut/wordpress-version-checker@v2.2.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
